{
 "title": "Dashboard OLT ZTE C3x ",
 "tags": [
  "olt",
  "zte",
  "gpon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "OLT",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; justify-content: space-between; width: 100%; padding: 10px;\">\n    <!-- Imagem à esquerda -->\n    <img src=\"https://mkt2.sobralnet.com.br/wp-content/uploads/2023/09/logo_horizontal.png\" alt=\"Logo\" style=\"max-height: 60px;\">\n\n    <!-- Título centralizado -->\n    <div style=\"flex-grow: 1; text-align: center;\">\n        <h2 style=\"color: #ffffff; font-size: 40px; font-weight: bold; margin: 0;\">MONITOR OLT ZTE</h2>\n    </div>\n\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"\ndisplay: flex;\nalign-items: center;\njustify-content: space-between;\nfont-size: 20px;\nfont-family: Impact;\nborder-radius: 0px 50px 0px 50px;\nbackground: linear-gradient(100deg, rgba(173, 216, 230, 0.3) 20%, rgb(135, 206, 250) 60%);\npadding: 02px;\">\n\n\n\n    <div style=\"text-align: center; flex-grow: 1;\">\n      <span style=\"color: black;\">STATUS</span>\n      <span style=\"color: #0047AB;\">|</span>\n      <span style=\"color: black;\">ONUS</span>\n    </div> \n\n\n</div>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 4 },
   "options": {
    "content": "<div style=\"\ndisplay: flex;\nalign-items: center;\njustify-content: space-between;\nfont-size: 20px;\nfont-family: Impact;\nborder-radius: 0px 50px 0px 50px;\nbackground: linear-gradient( 100deg, rgb(135, 206, 250) 20%, rgba(173, 216, 230, 0.3) 60%);\npadding: 02px;\">\n\n\n\n    <div style=\"text-align: center; flex-grow: 1;\">\n      <span style=\"color: black;\">STATUS</span>\n      <span style=\"color: #0047AB;\">|</span>\n      <span style=\"color: black;\">HARDWARE</span>\n    </div> \n\n\n</div>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 4 },
   "options": {
    "content": "<div style=\"\ndisplay: flex;\nalign-items: center;\njustify-content: space-between;\nfont-size: 20px;\nfont-family: Impact;\nborder-radius: 0px 50px 0px 50px;\nbackground: linear-gradient(100deg, rgba(173, 216, 230, 0.3) 20%, rgb(135, 206, 250) 60%);\npadding: 02px;\">\n\n\n\n    <div style=\"text-align: center; flex-grow: 1;\">\n      <span style=\"color: black;\">STATUS</span>\n      <span style=\"color: #0047AB;\">|</span>\n      <span style=\"color: black;\">CARDS</span>\n    </div> \n\n\n</div>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://cdn-icons-png.flaticon.com/512/4413/4413923.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}</span>\n        <span class=\"adapted-name\">N/AUTORIZADAS</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "PON gpon_1/1/10" },
     "itemTag": { "filter": "ONUs Onlines" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://cdn-icons-png.flaticon.com/512/8820/8820158.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}</span>\n        <span class=\"adapted-name\">AUTORIZADAS</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs Autorizadas" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://cdn-icons-png.flaticon.com/512/6689/6689985.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}</span>\n        <span class=\"adapted-name\">ONUS LOSS</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs LOS" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 6 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "Temperatura" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 6 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://cdn-icons-png.flaticon.com/512/1892/1892518.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}%</span>\n        <span class=\"adapted-name\">USO DE CPU</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "Uso de CPU Card 1" },
     "itemTag": { "filter": "Uso de CPU" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "dataset": "zabbix",
     "rawSql": "SELECT\r\n  REPLACE(REPLACE(REPLACE(it.name, 'Nome ', ''), 'Uso de CPU ', ''), 'Uso de Memoria ', '') AS item,\r\n  MAX(CASE WHEN it.name LIKE '%Nome%' THEN hx.value END) AS card,\r\n  MAX(CASE WHEN it.name LIKE '%Uso de CPU%' THEN hu.value END) AS cpu,\r\n  MAX(CASE WHEN it.name LIKE '%Uso de Memoria%' THEN hu.value END) AS memoria\r\nFROM\r\n  items it\r\n  INNER JOIN hosts ht ON ht.hostid = it.hostid\r\n  LEFT JOIN (\r\n    SELECT itemid, MAX(clock) AS max_clock\r\n    FROM history_uint\r\n    GROUP BY itemid\r\n  ) AS max_hu ON it.itemid = max_hu.itemid\r\n  LEFT JOIN history_uint hu ON hu.itemid = max_hu.itemid AND hu.clock = max_hu.max_clock\r\n  LEFT JOIN (\r\n    SELECT itemid, MAX(clock) AS max_clock\r\n    FROM history_text\r\n    GROUP BY itemid\r\n  ) AS max_hx ON it.itemid = max_hx.itemid\r\n  LEFT JOIN history_text hx ON hx.itemid = max_hx.itemid AND hx.clock = max_hx.max_clock\r\nWHERE\r\n  it.flags IN (0, 4)\r\n  AND it.status = 0\r\n  AND ht.status = 0\r\n  AND ht.host IN (\"$host\")\r\n  AND (\r\n    it.name LIKE '%Nome%'\r\n    OR it.name LIKE '%Uso de CPU%'\r\n    OR it.name LIKE '%Uso de Memoria%'\r\n  )\r\nGROUP BY\r\n  item\r\nORDER BY\r\n  item;\r\n"
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://images.vexels.com/media/users/3/205387/isolated/preview/9e5a4a16e78a187fc3e47fc6e2c5f03a-traco-do-icone-do-site-da-internet.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}</span>\n        <span class=\"adapted-name\">ONUS ONLINE</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs Onlines" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://cdn-icons-png.flaticon.com/512/4178/4178461.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}</span>\n        <span class=\"adapted-name\">DYINGGASP</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs DyingGasp" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://cdn-icons-png.flaticon.com/512/6514/6514577.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}</span>\n        <span class=\"adapted-name\">ONUS OFFLINE</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs OFF" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 9 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n\n<body>\n  <div class=\"adapted-container\">\n    <img src=\"https://static.vecteezy.com/system/resources/previews/059/438/689/non_2x/magnificent-minimalist-ram-module-for-computer-memory-original-free-png.png\" alt=\"Adapted Image\" class=\"adapted-image\">\n    <div class=\"adapted-content\">\n      <div class=\"adapted-value-container\">\n        <span class=\"adapted-value\">{{data.[0].[0].Value}}%</span>\n        <span class=\"adapted-name\">USO DE MEMORIA</span>\n      </div>\n    </div>\n  </div>\n</body>\n\n</html>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "OLT-ZTE" },
     "item": { "filter": "Uso de Memoria Card 1" },
     "itemTag": { "filter": "Uso de Memoria" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Visão Geral por PON",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  it.name AS nome_item,\r\n  MAX(CASE WHEN itg.tag LIKE '%ONUs Autorizadas%' THEN hu.value END) AS autorizadas,\r\n  MAX(CASE WHEN itg.tag LIKE '%ONUs Onlines%' THEN hu.value END) AS onlines,\r\n  MAX(CASE WHEN itg.tag LIKE '%ONUs OFF%' THEN hu.value END) AS offlines,\r\n  MAX(CASE WHEN itg.tag LIKE '%ONUs LOS%' THEN hu.value END) AS los,\r\n  MAX(CASE WHEN itg.tag LIKE '%ONUs DyingGasp%' THEN hu.value END) AS dyinggasp,\r\n  DATE_FORMAT(FROM_UNIXTIME(MAX(hu.clock)), '%d-%m-%Y %H:%i:%s') AS ultima_verificacao\r\nFROM\r\n  items it\r\n  INNER JOIN hosts ht ON ht.hostid = it.hostid\r\n  INNER JOIN item_tag itg ON itg.itemid = it.itemid\r\n  LEFT JOIN (\r\n    SELECT itemid, MAX(clock) AS max_clock\r\n    FROM history_uint\r\n    GROUP BY itemid\r\n  ) AS max_hu ON it.itemid = max_hu.itemid\r\n  LEFT JOIN history_uint hu ON hu.itemid = max_hu.itemid AND hu.clock = max_hu.max_clock\r\nWHERE\r\n  it.flags IN (0, 4)\r\n  AND it.status = 0\r\n  AND ht.status = 0\r\n  AND ht.host IN (\"$host\")\r\n  AND it.name LIKE '%PON gpon%'\r\nGROUP BY\r\n  it.name\r\nORDER BY\r\n  it.name;\r\n"
    }
   ]
  },
  {
   "title": "Historico de ONUs Onlines",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs Onlines" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Historico de ONUs Los",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs LOS" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Historico de ONUs Energia",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs DyingGasp" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Historico de ONUs Offlines",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$host: /",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "OLT" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "ONUs OFF" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Análise de Interfaces (Uplinks)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "zabbix",
     "rawSql": "WITH\r\n-- Subconsulta para obter os valores máximos de history_uint\r\nmax_hu AS (\r\n  SELECT\r\n    hu.itemid,\r\n    MAX(hu.clock) AS max_clock\r\n  FROM\r\n    history_uint hu\r\n    INNER JOIN items it ON it.itemid = hu.itemid\r\n    INNER JOIN hosts ht ON ht.hostid = it.hostid\r\n  WHERE\r\n    ht.name IN (\"$host\")\r\n  GROUP BY\r\n    hu.itemid\r\n),\r\n-- Subconsulta para obter os valores máximos de history\r\nmax_h AS (\r\n  SELECT\r\n    h.itemid,\r\n    MAX(h.clock) AS max_clock\r\n  FROM\r\n    history h\r\n    INNER JOIN items it ON it.itemid = h.itemid\r\n    INNER JOIN hosts ht ON ht.hostid = it.hostid\r\n  WHERE\r\n    ht.name IN (\"$host\")\r\n  GROUP BY\r\n    h.itemid\r\n),\r\n-- Subconsulta principal para agregar os dados necessários\r\ndados_agrupados AS (\r\n  SELECT\r\n    ht.name AS host,\r\n    REPLACE(\r\n      REPLACE(\r\n        REPLACE(\r\n          REPLACE(\r\n            REPLACE(\r\n              REPLACE(\r\n                REPLACE(\r\n                  REPLACE(\r\n                    REPLACE(\r\n                      REPLACE(\r\n                        REPLACE(\r\n                          REPLACE(\r\n                            REPLACE(\r\n                              REPLACE(\r\n                                REPLACE(\r\n                                  REPLACE(\r\n                                    REPLACE(\r\n                                      REPLACE(\r\n                                        REPLACE(\r\n                                          REPLACE(it.name, 'Interface ', ''),\r\n                                          ': Bits sent', ''\r\n                                        ),\r\n                                        ': Bits received', ''\r\n                                      ),\r\n                                      ': Operational status', ''\r\n                                    ),\r\n                                    ': Speed', ''\r\n                                  ),\r\n                                  ': Inbound packets discarded', ''\r\n                                ),\r\n                                ': Outbound packets discarded', ''\r\n                              ),\r\n                              ': Inbound packets with errors', ''\r\n                            ),\r\n                            ': Outbound packets with errors', ''\r\n                          ),\r\n                          ': RX Power Avg Lane 1-4', ''\r\n                        ),\r\n                        ': TX Power Avg Lane 1-4', ''\r\n                      ),\r\n                      ': RX Power', ''\r\n                    ),\r\n                    ': TX Power', ''\r\n                  ),\r\n                  ' Lane 1', ''\r\n                ),\r\n                ' Lane 2', ''\r\n              ),\r\n              ' Lane 3', ''\r\n            ),\r\n            ' Lane 4', ''\r\n          ),\r\n          ': Sinal RX', ''\r\n        ),\r\n        ': Sinal TX', ''\r\n      ),\r\n      ': Distancia', ''\r\n    ) AS interface,\r\n    MAX(CASE WHEN it.name LIKE '%Bits sent%' THEN hu.value END) AS bitsin,\r\n    MAX(CASE WHEN it.name LIKE '%Bits received%' THEN hu.value END) AS bitsout,\r\n    MAX(CASE WHEN it.name LIKE '%Operational status%' THEN hu.value END) AS status,\r\n    MAX(CASE WHEN it.name LIKE '%: Speed' THEN hu.value END) AS speed,\r\n    MAX(CASE WHEN it.name LIKE '%Bits sent%' THEN hu.value END) / NULLIF(MAX(CASE WHEN it.name LIKE '%: Speed' THEN hu.value END), 0) * 100 AS usoin,\r\n    MAX(CASE WHEN it.name LIKE '%Bits received%' THEN hu.value END) / NULLIF(MAX(CASE WHEN it.name LIKE '%: Speed' THEN hu.value END), 0) * 100 AS usoout,\r\n    COALESCE(\r\n      MAX(CASE WHEN it.name LIKE '%: RX Power%' THEN h.value END),\r\n      MAX(CASE WHEN it.name LIKE '%: RX Power Avg%' THEN h.value END),\r\n      MAX(CASE WHEN it.name LIKE '%: Sinal RX%' THEN h.value END)\r\n    ) AS rxpower,\r\n    COALESCE(\r\n      MAX(CASE WHEN it.name LIKE '%: TX Power%' THEN h.value END),\r\n      MAX(CASE WHEN it.name LIKE '%: TX Power Avg%' THEN h.value END),\r\n      MAX(CASE WHEN it.name LIKE '%: Sinal TX%' THEN h.value END)\r\n    ) AS txpower,\r\n    MAX(CASE WHEN it.name LIKE '%Distancia%' THEN hu.value END) AS distancia,\r\n    MAX(DATE_FORMAT(FROM_UNIXTIME(hu.clock), '%d-%m-%Y %H:%i:%s')) AS ultverificacao\r\n  FROM\r\n    items it\r\n    INNER JOIN hosts ht ON it.hostid = ht.hostid AND ht.name IN (\"$host\") AND ht.status = 0\r\n    LEFT JOIN max_hu ON it.itemid = max_hu.itemid\r\n    LEFT JOIN history_uint hu ON max_hu.itemid = hu.itemid AND max_hu.max_clock = hu.clock\r\n    LEFT JOIN max_h ON it.itemid = max_h.itemid\r\n    LEFT JOIN history h ON max_h.itemid = h.itemid AND max_h.max_clock = h.clock\r\n  WHERE\r\n    it.flags IN (0, 4)\r\n    AND (it.name LIKE '%ethernet%' OR it.name LIKE '%xgei%')\r\n    AND (\r\n      it.name LIKE '%Bits%'\r\n      OR it.name LIKE '%: Operational status%'\r\n      OR it.name LIKE '%: Speed'\r\n      OR it.name LIKE '%errors%'\r\n      OR it.name LIKE '%discarded%'\r\n      OR it.name LIKE '%Sinal RX%'\r\n      OR it.name LIKE '%Sinal TX%'\r\n      OR it.name LIKE '%RX Power%'\r\n      OR it.name LIKE '%TX Power%'\r\n      OR it.name LIKE '%Distancia%'\r\n    )\r\n  GROUP BY\r\n    interface,\r\n    host\r\n)\r\n-- Consulta final para adicionar os limites e status\r\nSELECT\r\n  *,\r\n  CASE\r\n    WHEN interface LIKE '%xgei%' AND distancia = 10 THEN '0.00 a -9.00'\r\n    WHEN interface LIKE '%xgei%' AND distancia = 40 THEN '-2.00 a -13.00'\r\n    WHEN interface LIKE '%xgei%' AND distancia = 80 THEN '-7.00 a -23.00'\r\n    WHEN interface LIKE '%ethernet%' AND distancia = 10 THEN '-1.00 a -11.00'\r\n    WHEN interface LIKE '%ethernet%' AND distancia = 40 THEN '0.99 a -17.79'\r\n    WHEN interface LIKE '%ethernet%' AND distancia = 80 THEN '-5.00 a -26.02'\r\n    ELSE NULL\r\n  END AS limiterx,\r\n  CASE\r\n    WHEN interface LIKE '%xgei%' AND distancia = 10 AND (rxpower < -9.00 OR rxpower > 0.00) THEN 'anormal'\r\n    WHEN interface LIKE '%xgei%' AND distancia = 40 AND (rxpower < -13.00 OR rxpower > -2.00) THEN 'anormal'\r\n    WHEN interface LIKE '%xgei%' AND distancia = 80 AND (rxpower < -23.00 OR rxpower > -7.00) THEN 'anormal'\r\n    WHEN interface LIKE '%ethernet%' AND distancia = 10 AND (rxpower < -11.00 OR rxpower > -1.00) THEN 'anormal'\r\n    WHEN interface LIKE '%ethernet%' AND distancia = 40 AND (rxpower < -17.79 OR rxpower > 0.99) THEN 'anormal'\r\n    WHEN interface LIKE '%ethernet%' AND distancia = 80 AND (rxpower < -26.02 OR rxpower > -5.00) THEN 'anormal'\r\n    ELSE 'normal'\r\n  END AS staturx\r\nFROM\r\n  dados_agrupados\r\nORDER BY\r\n  interface;\r\n"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "OLT" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Bits/" },
     "itemTag": { "filter": "Network Interfaces Bits" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Painel de Incidentes - OLT",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "OLT" },
     "host": { "filter": "$host" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}